# Site
repository: Taniksh12/Resume
# favicon: images/favicon.ico

# Personal info
name: Taniksh Gupta
title: Full Stack and Android Developer
email: taniksh101099@gmail.com
website: www.github.com/Taniksh12/Resume

# Social links
twitter_username: TanikshG
github_username:  Taniksh12
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: tanikshgupta
linkedin_username: taniksh-gupta-712175171
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Taniksh and I'm a engineering student. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
